replicaCount: 3

image:
  repository: syamlogi/http_app
  tag: "11025-v1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  ClassName: nginx
  host: web.example.com
  path: /
  pathType: Prefix

appMessage: "Hi Folks"

resources: {}

